Ecommerce-Project/Models/Cart.cs
namespace Ecommerce_Project.Models
{
    public class Cart
    {
        public int Id { get; set; }
        public List<CartItem> CartItems { get; set; }
    }
}

Ecommerce-Project/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Ecommerce_Project.Models;
using Microsoft.EntityFrameworkCore;

namespace Ecommerce_Project.Controllers
{
    public class CartController : Controller
    {
        private readonly ApplicationContext Context;

        public CartController(ApplicationContext _context)
        {
            Context = _context;
        }

        public IActionResult Index()
        {
            // Hämtar cart med id 1 och tillhörande cartitems och produkter. Produkter nås via relationen i CartItems
            Cart cart = Context.Carts.Include(c => c.CartItems).ThenInclude(p => p.Product).FirstOrDefault();

            // Skapar cart om den inte finns, (vi har dock seedat den).
            if (cart == null)
            {
                Cart newCart = new Cart();
                Context.Carts.Add(newCart);
                Context.SaveChanges();
            }
            return View(cart);
        }

        [HttpPost]
        public IActionResult AddToCart(int productId, int quantity = 1, string returnUrl = "adressurl")
        {
            // Hämtar Cart från databasen med id 1
            Cart cart = Context.Carts.Include(c => c.CartItems).FirstOrDefault(c => c.Id == 1);

            // Hämtar CartItem från Cart baserat på productId
            CartItem cartItem = cart.CartItems.FirstOrDefault(c => c.ProductId == productId);

            // Undersöker om cartItem redan finns i kundvagnen
            if (cartItem != null)
            {
                // Ökar mängden av en befintlig produkt i kundvagnen om den redan finns och uppdaterar i databasen
                cartItem.Quantity += quantity;
                Context.Update(cartItem);
                Context.SaveChanges();
            }
            else
            {
                // Skapar ett nytt CartItem-objekt, tilldelar egenskaperna och lägger till det i kundvagnen i databasen.
                cartItem = new CartItem();
                cartItem.ProductId = productId;
                cartItem.Quantity = quantity;
                cartItem.CartId = cart.Id;
                cart.CartItems.Add(cartItem);
                Context.SaveChanges();
            }

            return Redirect(returnUrl);
        }


        [HttpPost]
        public IActionResult DeleteCartItem(int removeId)
        {
            Cart cart = Context.Carts.Include(c => c.CartItems).ThenInclude(ci => ci.Product).FirstOrDefault(c => c.Id == 1);
            CartItem cartItem = cart.CartItems.FirstOrDefault(c => c.Id == removeId);

            Context.CartItems.Remove(cartItem);
            Context.SaveChanges();

            // Indexvyn i Cart använder modellen Cart
            return View("Index", cart); 
        }

        [HttpPost]
        public IActionResult EmptyCart (int emptyCart)
        {
            Cart cart = Context.Carts.Include(c => c.CartItems).ThenInclude(ci => ci.Product).FirstOrDefault(c => c.Id == emptyCart);

            // Skapar en lista med alla cartitems som tillhör den kundvagn med id emptyCart.
            List<CartItem> cartItem = cart.CartItems.ToList();

            // Loopar över listan och tar bort dom från databasen
            foreach (CartItem item in cartItem)
            {
                Context.CartItems.Remove(item);
            }
            Context.SaveChanges();
            return View("Index", cart);
        }

        // Incrementsmetod som används direkt i kundvagnsvyn (+)
        [HttpPost]
        public IActionResult IncrementProductInCart(int productId)
        {
            Cart cart = Context.Carts.Include(c => c.CartItems).ThenInclude(ci => ci.Product).FirstOrDefault(c => c.Id == 1);
            CartItem cartItem = cart.CartItems.FirstOrDefault(c => c.ProductId == productId);

            // Öka med 1 och uppdaterar databasen
            cartItem.Quantity ++;
            Context.Update(cartItem);
            Context.SaveChanges();
            return View("Index", cart);
        }

        // Decrementsmetod som används direkt i kundvagnsvyn (-)
        [HttpPost]
        public IActionResult DecrementProductInCart(int productId)
        {
            Cart cart = Context.Carts.Include(c => c.CartItems).ThenInclude(ci => ci.Product).FirstOrDefault(c => c.Id == 1);
            CartItem cartItem = cart.CartItems.FirstOrDefault(c => c.ProductId == productId);

            // Minskar med 1 och uppdaterar databasen
            cartItem.Quantity--;
            Context.Update(cartItem);
            Context.SaveChanges();
            return View("Index", cart);
        }
    }
}

Ecommerce-Project/Controllers/CheckoutController.cs
using Ecommerce_Project.Models;
using Ecommerce_Project.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Ecommerce_Project.Controllers
{
    public class CheckoutController : Controller
    {
        private readonly ApplicationContext _context;

        public CheckoutController(ApplicationContext context)
        {
            _context = context;
        }

        public IActionResult Index(int cartId)
        {
            Cart cart = _context.Carts.Include(c => c.CartItems).ThenInclude(ci => ci.Product).FirstOrDefault(c => c.Id == cartId);

            OrderCartItem orderCartView = new OrderCartItem();
            orderCartView.Order = new Order();
            orderCartView.CartItems = cart.CartItems;
            return View(orderCartView);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SubmitOrder(OrderCartItem viewModel, int cartId)
        {
			// Räkna ut totalpriset på ordern + frakt
			decimal totalPriceSEK = viewModel.CartItems.Sum(ci => ci.Product.PriceSEK * ci.Quantity) + viewModel.Order.ShippingRate;
			viewModel.Order.TotalPriceSEK = totalPriceSEK;
			viewModel.Order.TotalPriceEUR = totalPriceSEK * 0.1m;
			// Spara beställningen till databasen
			_context.Orders.Add(viewModel.Order);
            _context.SaveChanges();

            // Skapa OrderItems för varje CartItem
            foreach (CartItem cartItem in viewModel.CartItems)
            {
                OrderItem orderItem = new OrderItem();
                orderItem.OrderId = viewModel.Order.Id;
                orderItem.ProductId = cartItem.ProductId;
                orderItem.Quantity = cartItem.Quantity;


                // Spara OrderItem till databasen
                _context.OrderItems.Add(orderItem);
            }

            // Spara ändringarna i databasen
            _context.SaveChanges();

             // Ta bort alla CartItems från användarens kundvagn
             List<CartItem> cartItemsToRemove = _context.CartItems.Where(ci => ci.CartId == viewModel.CartId).ToList();
             foreach (var cartItem in cartItemsToRemove)
             {
                  _context.CartItems.Remove(cartItem);
             }
              _context.SaveChanges();

            // Skicka kunden till startsidan om allt går igenom
            return View("Thanks", viewModel);

        }
    }
}

Ecommerce-Project/Views/Cart/Index.cshtml
@model Cart

<h1>Kundvagnen</h1>

<table class="table">
    <thead>
        <tr>
            <th>Produkt</th>
            <th><span class="ms-3">Antal</span></th>
            <th>Pris</th>
            <th>Totalt</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (CartItem cartItem in Model.CartItems)
        {
            <tr>
                <td>@cartItem.Product.Name</td>
                <td>
                    <div class="d-flex align-items-center gap-2">
                        <form asp-action="DecrementProductInCart" asp-controller="Cart" method="POST">
                            <input hidden name="productId" value="@cartItem.ProductId">
                            <button type="submit" class="btn btn-primary btn-sm" style="width: 27px;">-</button>
                        </form>
                        @cartItem.Quantity
                        <form asp-action="IncrementProductInCart" asp-controller="Cart" method="POST">
                            <input hidden name="productId" value="@cartItem.ProductId">
                            <button type="submit" class="btn btn-primary btn-sm" style="width: 27px;">+</button>
                        </form>
                    </div>
                </td>
                <td>@cartItem.Product.PriceSEK</td>
                <td>@(cartItem.Quantity * @cartItem.Product.PriceSEK)</td>
                <form asp-action="DeleteCartItem" asp-controller="Cart" method="POST">
                    <input hidden name="removeId" value="@cartItem.Id">
                    <td><input type="submit" class="btn btn-primary" value="Ta bort från kundvagn" /></td>
                </form>
            </tr>
        }
    </tbody>
</table>
<div class="d-flex justify-content-between">
    <form asp-action="EmptyCart" asp-controller="Cart" method="POST" style="display:inline;">
        <input hidden name="emptyCart" value="@Model.Id">
        <input type="submit" class="btn btn-danger" value="Rensa kundvagn" />
    </form>

    <form asp-action="Index" asp-controller="Checkout" method="POST" style="display:inline;">
        <input hidden name="cartId" value="@Model.Id">
        <input type="submit" class="btn btn-success" value="Checka ut" />
    </form>
</div>