Ecommerce-Project/Models/Product.cs
namespace Ecommerce_Project.Models
{
    public class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal PriceSEK { get; set; }
        public decimal PriceEUR { get; set; }
        public string ImgUrl { get; set; }
        public List<Category> Categories { get; set; }
        public List<Tag> Tags { get; set; }
        public List<CartItem> CartItems { get; set; }
    }
}

Ecommerce-Project/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Ecommerce_Project.Models;
using Microsoft.EntityFrameworkCore;

namespace Ecommerce_Project.Controllers
{
    public class CartController : Controller
    {
        private readonly ApplicationContext Context;

        public CartController(ApplicationContext _context)
        {
            Context = _context;
        }

        public IActionResult Index()
        {
            // Hämtar cart med id 1 och tillhörande cartitems och produkter. Produkter nås via relationen i CartItems
            Cart cart = Context.Carts.Include(c => c.CartItems).ThenInclude(p => p.Product).FirstOrDefault();

            // Skapar cart om den inte finns, (vi har dock seedat den).
            if (cart == null)
            {
                Cart newCart = new Cart();
                Context.Carts.Add(newCart);
                Context.SaveChanges();
            }
            return View(cart);
        }

        [HttpPost]
        public IActionResult AddToCart(int productId, int quantity = 1, string returnUrl = "adressurl")
        {
            // Hämtar Cart från databasen med id 1
            Cart cart = Context.Carts.Include(c => c.CartItems).FirstOrDefault(c => c.Id == 1);

            // Hämtar CartItem från Cart baserat på productId
            CartItem cartItem = cart.CartItems.FirstOrDefault(c => c.ProductId == productId);

            // Undersöker om cartItem redan finns i kundvagnen
            if (cartItem != null)
            {
                // Ökar mängden av en befintlig produkt i kundvagnen om den redan finns och uppdaterar i databasen
                cartItem.Quantity += quantity;
                Context.Update(cartItem);
                Context.SaveChanges();
            }
            else
            {
                // Skapar ett nytt CartItem-objekt, tilldelar egenskaperna och lägger till det i kundvagnen i databasen.
                cartItem = new CartItem();
                cartItem.ProductId = productId;
                cartItem.Quantity = quantity;
                cartItem.CartId = cart.Id;
                cart.CartItems.Add(cartItem);
                Context.SaveChanges();
            }

            return Redirect(returnUrl);
        }


        [HttpPost]
        public IActionResult DeleteCartItem(int removeId)
        {
            Cart cart = Context.Carts.Include(c => c.CartItems).ThenInclude(ci => ci.Product).FirstOrDefault(c => c.Id == 1);
            CartItem cartItem = cart.CartItems.FirstOrDefault(c => c.Id == removeId);

            Context.CartItems.Remove(cartItem);
            Context.SaveChanges();

            // Indexvyn i Cart använder modellen Cart
            return View("Index", cart); 
        }

        [HttpPost]
        public IActionResult EmptyCart (int emptyCart)
        {
            Cart cart = Context.Carts.Include(c => c.CartItems).ThenInclude(ci => ci.Product).FirstOrDefault(c => c.Id == emptyCart);

            // Skapar en lista med alla cartitems som tillhör den kundvagn med id emptyCart.
            List<CartItem> cartItem = cart.CartItems.ToList();

            // Loopar över listan och tar bort dom från databasen
            foreach (CartItem item in cartItem)
            {
                Context.CartItems.Remove(item);
            }
            Context.SaveChanges();
            return View("Index", cart);
        }

        // Incrementsmetod som används direkt i kundvagnsvyn (+)
        [HttpPost]
        public IActionResult IncrementProductInCart(int productId)
        {
            Cart cart = Context.Carts.Include(c => c.CartItems).ThenInclude(ci => ci.Product).FirstOrDefault(c => c.Id == 1);
            CartItem cartItem = cart.CartItems.FirstOrDefault(c => c.ProductId == productId);

            // Öka med 1 och uppdaterar databasen
            cartItem.Quantity ++;
            Context.Update(cartItem);
            Context.SaveChanges();
            return View("Index", cart);
        }

        // Decrementsmetod som används direkt i kundvagnsvyn (-)
        [HttpPost]
        public IActionResult DecrementProductInCart(int productId)
        {
            Cart cart = Context.Carts.Include(c => c.CartItems).ThenInclude(ci => ci.Product).FirstOrDefault(c => c.Id == 1);
            CartItem cartItem = cart.CartItems.FirstOrDefault(c => c.ProductId == productId);

            // Minskar med 1 och uppdaterar databasen
            cartItem.Quantity--;
            Context.Update(cartItem);
            Context.SaveChanges();
            return View("Index", cart);
        }
    }
}

Ecommerce-Project/Controllers/ProductsController.cs
using Ecommerce_Project.Models;
using Ecommerce_Project.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Ecommerce_Project.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ApplicationContext Context;

        public ProductsController(ApplicationContext _context)
        {
            Context = _context;
        }

        public IActionResult Index()
        {
            // Hämtar en lista över Category-objekt och inkludera relaterade produkter och taggar.
            List<Category> categoriesProductsTags = Context.Categories.Include(c => c.Products).ThenInclude(p => p.Tags).ToList();

            return View(categoriesProductsTags);
        }

        // Egen vy för att visa valuta i euro.
        public IActionResult IndexEUR()
        {
            List<Category> categoriesWithProducts = Context.Categories.Include(c => c.Products).ThenInclude(p => p.Tags).ToList();

            return View(categoriesWithProducts);
        }

        public IActionResult Create()
        {
            // Hämtar en lista av alla kategorier och taggar för ge möjlighet att välja flera i drop-down menyer med checkboxes.
            CategoriesAndTags ShowCategoryAndTags = new CategoriesAndTags();
            ShowCategoryAndTags.Categories = Context.Categories.ToList();
            ShowCategoryAndTags.Tags = Context.Tags.ToList();
            return View(ShowCategoryAndTags);
        }

        [HttpPost]
        // Stränglistorna är till för att kunna skicka flera kategorier och taggar
        public IActionResult Create(List<string> categoryName, string Name, string Description, decimal Price, string ImgUrl, List<string> tagName)
        {
            // Skapa en ny produktinstans
            Product NewProduct = new Product();
            NewProduct.Name = Name;
            NewProduct.Description = Description;
            NewProduct.PriceSEK = Price;

            // Växla till euro med fast växelkurs
            NewProduct.PriceEUR = Price * 0.1m;

            NewProduct.ImgUrl = ImgUrl;
            NewProduct.Categories = new List<Category>();
            NewProduct.Tags = new List<Tag>();

            // Lägg till kategorin baserat på namn
            foreach (var name in categoryName)
            {
                var category = Context.Categories.FirstOrDefault(c => c.Name == name);
                if (category != null)
                {
                    NewProduct.Categories.Add(category);
                }
            }

            foreach (var name in tagName)
            {
                var tag = Context.Tags.FirstOrDefault(t => t.Name == name);
                if (tag != null)
                {
                    NewProduct.Tags.Add(tag);
                }
            }

            // Lägg till den nya produkten i databasen
            Context.Products.Add(NewProduct);
            Context.SaveChanges();

            return RedirectToAction("Create");
        }

        public IActionResult Details(int productId)
        {
            Product product = Context.Products.Include(c => c.Categories).FirstOrDefault(p => p.Id == productId);

            return View(product);
        }

        public IActionResult DetailsEUR(int productId)
        {
            Product product = Context.Products.FirstOrDefault(p => p.Id == productId);

            return View(product);
        }

        public IActionResult AddCategory()
        {
            return View();
        }

        // Lägg till kategorifunktion
        [HttpPost]
        public IActionResult AddCategory(string Name) 
        { 
            Category Newcategory = new Category();
            Newcategory.Name = Name;
            Context.Categories.Add(Newcategory);
            Context.SaveChanges();
            return RedirectToAction("Create");
        }

        public IActionResult AddTags() 
        {
            return View();
        }

        // Lägg till tagsfunktion
        [HttpPost]
        public IActionResult AddTags(string name)
        {
            Tag NewTag = new Tag();
            NewTag.Name = name;
            Context.Tags.Add(NewTag);
            Context.SaveChanges();
            return RedirectToAction("Create");
        }

    }
}

Ecommerce-Project/Views/Products/AddCategory.cshtml
<h1>Lägg till Kategori</h1>

<form asp-route="AddCategory" method="POST">

    <div class="form-group">
        <label for="name">Namn:</label>
        <input type="text" name="Name" id="name" class="form-control" />
    </div>
    <input class="btn btn-primary mt-2" type="submit" value="Lägg till" />

</form>

Ecommerce-Project/Views/Products/AddTags.cshtml
<h1>Lägg till tags</h1>

<form asp-route="AddTags" method="POST">

    <div class="form-group">

        <label for="tagName">Namn: </label>
        <input type="text" name="name" id="tagName" class="form-control"/>
        <input type="submit" class="btn btn-primary mt-2" />
    </div>

</form>

Ecommerce-Project/Views/Products/Create.cshtml
@model Ecommerce_Project.Models.ViewModels.CategoriesAndTags;

<h1>Skapa ny produkt</h1>

<form asp-route="Create" method="POST">
    <div class="form-group">
        <label for="category">Kategori:</label>
        <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="category-dropdown" data-bs-toggle="dropdown" data-bs-haspopup="true" aria-expanded="false">
                Välj kategorier
            </button>
            <div class="dropdown-menu" aria-labelledby="category-dropdown">
                @foreach (var category in Model.Categories)
                {
                    <div class="dropdown-item">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="@category.Name" name="categoryName" value="@category.Name">
                            <label class="form-check-label" for="@category.Name">
                                @category.Name
                            </label>
                        </div>
                    </div>
                }
            </div>
        </div>
        <a asp-action="AddCategory" asp-controller="Products" class="btn btn-link">Lägg till nya kategorier</a>
    </div>
    <div class="form-group">
        <label for="name">Namn:</label>
        <input type="text" name="Name" id="name" class="form-control" required />
    </div>
    <div class="form-group">
        <label for="description">Beskrivning:</label>
        <input type="text" name="Description" id="description" class="form-control" required />
    </div>
    <div class="form-group">
        <label for="price">Pris:</label>
        <input type="number" name="Price" id="price" class="form-control" required />
    </div>
    <div class="form-group">
        <label for="imgUrl">Bildlänk:</label>
        <input type="text" name="ImgUrl" id="imgUrl" class="form-control" required />
    </div>
    <div class="form-group">
        <label for="tag">Taggar:</label>
        <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="tag-dropdown" data-bs-toggle="dropdown" data-bs-haspopup="true" aria-expanded="false">
                Välj taggar
            </button>
            <div class="dropdown-menu" aria-labelledby="tag-dropdown">
                @foreach (var tag in Model.Tags)
                {
                    <div class="dropdown-item">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="@tag.Name" name="tagName" value="@tag.Name">
                            <label class="form-check-label" for="@tag.Name">
                                @tag.Name
                            </label>
                        </div>
                    </div>
                }
            </div>
        </div>
        <a asp-action="AddTags" asp-controller="Products" class="btn btn-link">Lägg till nya taggar</a>
    </div>
    <input type="submit" value="Lägg till" class="btn btn-primary" />
</form>

Ecommerce-Project/Views/Products/Details.cshtml
@model Product

<h1>@Model.Name</h1>
<div class="row">
    <div class="col-md-6">
        <img src="@Model.ImgUrl" alt="@Model.Name" class="img-fluid">
        <br />
        <div>
            <a href="https://www.twitter.com" class="btn btn-primary mt-1">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-twitter" viewBox="0 0 16 16">
                    <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z" />
                </svg>
            </a>
            <a href="https://www.instagram.com" class="btn btn-danger mt-1">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
                    <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z" />
                </svg>
            </a>
        </div>
    </div>
    <div class="col-md-6">
        <h3>Beskrivning</h3>
        <p>@Model.Description</p>
        <h4>Pris</h4>
        <p>@Model.PriceSEK kr</p>
        <form asp-action="AddToCart" asp-controller="Cart" method="POST">
            <input type="hidden" name="productId" value="@Model.Id">
            <input type="hidden" name="returnUrl" value="@Url.Action("Details", "Products", new { productId = Model.Id })">
            <button type="submit" class="btn btn-primary">Lägg i varukorg</button>
        </form>
        <div class="mt-3">
            <a asp-action="DetailsEUR" asp-controller="Products" asp-route-productId="@Model.Id" class="btn btn-light">Visa priser i EUR</a>
        </div>
    </div>
</div>

Ecommerce-Project/Views/Products/DetailsEUR.cshtml
@model Product

<h1>@Model.Name</h1>
<div class="row">
    <div class="col-md-6">
        <img src="@Model.ImgUrl" alt="@Model.Name" class="img-fluid">
        <br />
        <div>
            <a href="https://www.twitter.com" class="btn btn-primary mt-1">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-twitter" viewBox="0 0 16 16">
                    <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z" />
                </svg>
            </a>
            <a href="https://www.instagram.com" class="btn btn-danger mt-1">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
                    <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z" />
                </svg>
            </a>
        </div>
    </div>
    <div class="col-md-6">
        <h3>Beskrivning</h3>
        <p>@Model.Description</p>
        <h4>Pris</h4>
        <p>@Model.PriceEUR €</p>
        <form asp-action="AddToCart" asp-controller="Cart" method="POST">
            <input type="hidden" name="productId" value="@Model.Id">
            <input type="hidden" name="returnUrl" value="@Url.Action("DetailsEUR", "Products", new { productId = Model.Id })">
            <button type="submit" class="btn btn-primary">Lägg i varukorg</button>
        </form>
        <div class="mt-3">
            <a asp-action="Details" asp-controller="Products" asp-route-productId="@Model.Id" class="btn btn-light">Visa priser i SEK</a>
        </div>
    </div>
</div>

Ecommerce-Project/Views/Products/Index.cshtml
@model List<Category>

<h1>Produkter</h1>

<div class="row">
    <div class="col-md-4 mb-4">
        <a asp-action="Create" class="btn btn-primary">Lägg till produkt</a>
        <a asp-action="IndexEUR" class="btn btn-light">Visa priser i EUR</a>
    </div>
</div>

@foreach (var category in Model)
{
    <h2>@category.Name</h2>
    <hr>
    <div class="row">
        @foreach (var product in category.Products)
        {
            <div class="col-md-4 mb-4">
                <div class="card">
                    <img class="card-img-top" src="@product.ImgUrl" alt="@product.Name">
                    <div class="card-body">
                        <h5 class="card-title">@product.Name</h5>
                        <p class="card-text">@product.Description</p>
                        <p><strong>Pris: </strong>@product.PriceSEK kr</p>
                        @if (product.Tags.Any())
                        {
                            <p>
                                <strong>Taggar: </strong>
                                @foreach (var tag in product.Tags)
                                {
                                    <span class="badge bg-dark">@tag.Name</span>
                                }
                            </p>
                        }
                        <form asp-action="AddToCart" asp-controller="Cart" method="POST">
                            <input type="hidden" name="productId" value="@product.Id">
                            <input type="hidden" name="returnUrl" value="@Url.Action("Index", "Products")">
                            <button type="submit" class="btn btn-success mb-1">Lägg i varukorg</button>
                        </form>
                        <form asp-action="Details" asp-controller="Products" method="POST">
                            <input type="hidden" name="productId" value="@product.Id">
                            <button type="submit" class="btn btn-primary">Detaljer</button>
                        </form>
                    </div>
                </div>
            </div>
        }
    </div>
}

Ecommerce-Project/Views/Products/IndexEUR.cshtml
@model List<Category>

<h1>Produkter</h1>

<div class="row">
    <div class="col-md-4 mb-4">
        <a asp-action="Create" class="btn btn-primary">Lägg till produkt</a>
        <a asp-action="Index" class="btn btn-light">Visa priser i SEK</a>
    </div>
</div>

@foreach (var category in Model)
{
    <h2>@category.Name</h2>
    <hr>
    <div class="row">
        @foreach (var product in category.Products)
        {
            <div class="col-md-4 mb-4">
                <div class="card">
                    <img class="card-img-top" src="@product.ImgUrl" alt="@product.Name">
                    <div class="card-body">
                        <h5 class="card-title">@product.Name</h5>
                        <p class="card-text">@product.Description</p>
                        <p><strong>Pris: </strong>@product.PriceEUR €</p>
                        @if (product.Tags.Any())
                        {
                            <p>
                                <strong>Taggar: </strong>
                                @foreach (var tag in product.Tags)
                                {
                                    <span class="badge bg-dark">@tag.Name</span>
                                }
                            </p>
                        }
                        <form asp-action="AddToCart" asp-controller="Cart" method="POST">
                            <input type="hidden" name="productId" value="@product.Id">
                            <input type="hidden" name="returnUrl" value="@Url.Action("IndexEUR", "Products")">
                            <button type="submit" class="btn btn-success mb-1">Lägg i varukorg</button>
                        </form>
                        <form asp-action="Details" asp-controller="Products" method="POST">
                            <input type="hidden" name="productId" value="@product.Id">
                            <button type="submit" class="btn btn-primary">Detaljer</button>
                        </form>
                    </div>
                </div>
            </div>
        }
    </div>
}