Ecommerce-Project/Models/Ticket.cs
namespace Ecommerce_Project.Models
{
    public class Ticket
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string UserEmail { get; set; }
        public List <TicketMessage> TicketMessages { get; set; }

    }
}

Ecommerce-Project/Controllers/TicketsController.cs
using Microsoft.AspNetCore.Mvc;
using Ecommerce_Project.Models;
using Microsoft.EntityFrameworkCore;

namespace Ecommerce_Project.Controllers
{
    public class TicketsController : Controller
    {
        private readonly ApplicationContext Context;

        public TicketsController(ApplicationContext _context)
        {
            Context = _context;
        }

        // Hämtar alla tickets från databasen och visar dem vyn.
        public IActionResult Index()
        {
            List<Ticket> tickets = Context.Tickets.ToList();
            return View(tickets);
        }

        // Visar en vy där användaren kan skapa en ny ticket.
        public IActionResult Create()
        {
            return View();
        }

        // Lägg till Ticket
        [HttpPost]
        public IActionResult Create(Ticket ticket)
        {
            Context.Add(ticket);
            Context.SaveChanges();
            return RedirectToAction("Create");
        }

        // Visar detaljer om en specifik Ticket baserat på ticketId
        public IActionResult Details(int ticketId)
        {
            Ticket ticket = Context.Tickets.Include(t => t.TicketMessages).FirstOrDefault(t => t.Id == ticketId);
            return View(ticket);
        }

        // Visar detaljer om en specifik Ticket och alla meddelanden som är kopplade till den, i en "admin-vy".
        public IActionResult DetailsAdmin(int ticketId)
        {
            Ticket ticket = Context.Tickets.Include(t => t.TicketMessages).FirstOrDefault(t => t.Id == ticketId);
            return View(ticket);
        }

        // Visar alla Tickets som är kopplade till en specifik användare (identifierad med email-adress).
        public IActionResult CustomerTickets(string email)
        {
            List<Ticket> tickets = Context.Tickets.Where(t => t.UserEmail == email).ToList();
            return View(tickets);
        }

        // Lägger till ett TicketMessage till en specifik Ticket (från en användare).
        [HttpPost]
        public IActionResult AddTicketMessageUser (int TicketId, string Text)
        {
            TicketMessage newMessage = new TicketMessage();
            newMessage.TicketId = TicketId;
            newMessage.Text = Text;
            newMessage.IsAdmin = false;
            Context.TicketMessages.Add(newMessage);
            Context.SaveChanges();

            return RedirectToAction("Details", newMessage);
        }

        // Lägger till ett TicketMessage till en specifik Ticket (från en "admin").
        [HttpPost]
        public IActionResult AddTicketMessageAdmin(int TicketId, string Text)
        {
            TicketMessage newMessage = new TicketMessage();
            newMessage.TicketId = TicketId;
            newMessage.Text = Text;
            newMessage.IsAdmin = true;
            Context.TicketMessages.Add(newMessage);
            Context.SaveChanges();

            return RedirectToAction("DetailsAdmin", newMessage);
        }

    }
}

Ecommerce-Project/Views/Tickets/Create.cshtml
<h1>Skapa ett nytt ärende</h1>

<form asp-route="Create" method="post">
    <div class="form-group">
        <label for="Title">Titel:</label>
        <input type="text" class="form-control" id="Title" name="Title" required>
    </div>
    <div class="form-group">
        <label for="Description">Beskrivning:</label>
        <textarea class="form-control" id="Description" name="Description" rows="5" required></textarea>
    </div>
    <div class="form-group">
        <label for="UserEmail">Din e-postadress:</label>
        <input type="email" class="form-control" id="UserEmail" name="UserEmail" required>
    </div>
    <button type="submit" class="btn btn-primary mt-1">Skapa ärende</button>
</form>

<hr>

<h2>Har du redan ett ärende?</h2>

<form asp-controller="Tickets" asp-action="CustomerTickets" method="get">
    <div class="form-group">
        <label for="UserEmail">Din e-postadress:</label>
        <input type="email" class="form-control" id="UserEmail" name="email" required>
    </div>
    <button type="submit" class="btn btn-primary mt-1">Visa dina ärenden</button>
</form>

<a class="btn btn-success mt-1" asp-area="" asp-controller="Tickets" asp-action="Index">Adminarea</a>

Ecommerce-Project/Views/Tickets/CustomerTickets.cshtml
@model List<Ticket>

<h1>Dina ärenden</h1>

@if (Model.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>Titel</th>
                <th>Beskrivning</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var ticket in Model)
            {
                <tr>
                    <td>@ticket.Title</td>
                    <td>@ticket.Description</td>
                    <td>

                        <form asp-action="Details" asp-controller="Tickets" method="POST">
                            <input type="hidden" name="ticketId" value="@ticket.Id">
                            <button type="submit" class="btn btn-primary">Gå till ticket</button>
                        </form>

                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Du har inga ärenden.</p>
}

Ecommerce-Project/Views/Tickets/Details.cshtml
@model Ticket

<div class="card">
    <div class="card-header">
        <h5 class="card-title">Titel: @Model.Title</h5>
        <h6 class="card-subtitle mb-2 text-muted">Kund: @Model.UserEmail</h6>
        <h6 class="card-subtitle mb-2 text-muted">Beskrivning: @Model.Description</h6>
    </div>
</div>

<h3 class="mt-4">Meddelanden:</h3>

<div class="list-group">
    @foreach (var message in Model.TicketMessages)
    {
        <div class="list-group-item list-group-item-action">
            @if (message.IsAdmin)
            {
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1 text-danger">Admin</h5>
                </div>
                <p class="mb-1">@message.Text</p>
            }
            else
            {
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1 text-success">Kund</h5>
                </div>
                <p class="mb-1 font-weight-bold">@message.Text</p>
            }
        </div>
    }
</div>

<h3 class="mt-4">Svara på ärende:</h3>

<form asp-action="AddTicketMessageUser" asp-controller="Tickets" method="POST">

    <input type="hidden" name="TicketId" value="@Model.Id" />
    <div class="form-group">
        <textarea class="form-control" name="Text"></textarea>
        <button type="submit" class="btn btn-primary mt-2">Skicka</button>
    </div>

</form>

Ecommerce-Project/Views/Tickets/DetailsAdmin.cshtml
@model Ticket

<div class="card">
    <div class="card-header">
        <h5 class="card-title">Titel: @Model.Title</h5>
        <h6 class="card-subtitle mb-2 text-muted">Kund: @Model.UserEmail</h6>
        <h6 class="card-subtitle mb-2 text-muted">Beskrivning: @Model.Description</h6>
    </div>
</div>

<h3 class="mt-4">Meddelanden:</h3>

<div class="list-group">
    @foreach (var message in Model.TicketMessages)
    {
        <div class="list-group-item list-group-item-action">
            @if (message.IsAdmin)
            {
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1 text-danger">Admin</h5>
                </div>
                <p class="mb-1">@message.Text</p>
            }
            else
            {
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1 text-success">Kund</h5>
                </div>
                <p class="mb-1 font-weight-bold">@message.Text</p>
            }
        </div>
    }
</div>

<h3 class="mt-4">Svara på ärende:</h3>

<form asp-action="AddTicketMessageAdmin" asp-controller="Tickets" method="POST">

    <input type="hidden" name="TicketId" value="@Model.Id" />
    <div class="form-group">
        <textarea class="form-control" name="Text"></textarea>
        <button type="submit" class="btn btn-primary mt-2">Skicka</button>
    </div>

</form>

Ecommerce-Project/Views/Tickets/Index.cshtml
@model List<Ticket>

<h1>Admin</h1>

<div class="row">
    @foreach (Ticket ticket in Model)
    {
        <div class="col-md-4 mb-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">@ticket.Title</h5>
                    <p class="card-text">@ticket.Description</p>
                    <p class="card-text"><strong>Email: </strong>@ticket.UserEmail</p>
                    <form asp-action="DetailsAdmin" asp-controller="Tickets" method="POST">
                        <input type="hidden" name="ticketId" value="@ticket.Id">
                        <button type="submit" class="btn btn-primary">Gå till ticket</button>
                    </form>
                </div>
            </div>
        </div>
    }
</div>